networks:
  aurora:
    external: false

services:
  db:
    image: mysql:latest
    networks:
      - aurora
    command: --authentication_policy=caching_sha2_password
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: aurora-stats
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db:/var/lib/mysql
  
  flyway:
    image: flyway/flyway
    networks:
      - aurora
    command: -url=jdbc:mysql://db:3306 -schemas=aurora-stats -user=root -password=dbpass -connectRetries=50 migrate
    volumes: 
      - ./mysql/migrations:/flyway/sql
    depends_on:
      - db

  api:
    networks:
      - aurora
    build:
      dockerfile: api.dockerfile
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: dbpass
      PORT: 8080
    ports:
      - 8080:8080
    depends_on:
      - db