networks:
  aurora:
    external: false

services:
  db:
    build:
      dockerfile: docker/db.dockerfile
    networks:
      - aurora
    command: ["--authentication_policy=caching_sha2_password"]
    environment:
      MYSQL_ROOT_PASSWORD: dbpass
      MYSQL_DATABASE: ${DATABASE}
      FLYWAY_USER: ${DB_FLYWAY_USER}
      FLYWAY_PASSWORD: ${DB_FLYWAY_PASSWORD}
      READ_USER: ${DB_READ_USER}
      READ_PASSWORD: ${DB_READ_PASSWORD}
      WRITE_USER: ${DB_WRITE_USER}
      WRITE_PASSWORD: ${DB_WRITE_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mysql/db:/var/lib/mysql
      - ./mysql/conf.d:/etc/mysql/conf.d
    restart: unless-stopped

  flyway:
    image: flyway/flyway
    networks:
      - aurora
    command: -url=jdbc:mysql://db:3306 -schemas=${DATABASE} -user=${DB_FLYWAY_USER} -password=${DB_FLYWAY_PASSWORD} -connectRetries=50 migrate
    volumes:
      - ./mysql/migrations:/flyway/sql
    depends_on:
      - db

  api:
    networks:
      - aurora
    build:
      dockerfile: docker/api.dockerfile
    environment:
      DB_NAME: ${DATABASE}
      DB_WRITE_USER: ${DB_WRITE_USER}
      DB_READ_USER: ${DB_READ_USER}
      DB_WRITE_HOST: db
      DB_READ_HOST: db
      DB_WRITE_PASSWORD: ${DB_WRITE_PASSWORD}
      DB_READ_PASSWORD: ${DB_READ_PASSWORD}
      PORT: ${API_PORT}
    ports:
      - ${API_PORT}:${API_PORT}
    depends_on:
      - db
    restart: unless-stopped

  website:
    networks:
      - aurora
    build:
      dockerfile: docker/website-dev.dockerfile
    volumes:
      - ./website:/app
    command: yarn dev
    environment:
      REACT_APP_API: ${API_URL}
      REACT_APP_API_PORT: ${API_PORT}
    ports:
      - ${WEBSITE_PORT}:${WEBSITE_PORT}
    depends_on:
      - api
    restart: unless-stopped

  # website:
  #   networks:
  #     - aurora
  #   build:
  #     dockerfile: docker/website-dev.dockerfile
  #   volumes:
  #     - ./website:/app
  #   command: yarn start
  #   environment:
  #     REACT_APP_API: https://stats.test-app-guea.test4.skybet.net/aurora-api
  #   ports:
  #     - 3000:3000
  #   # depends_on:
  #   #   - api
  #   restart: unless-stopped
