package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"aurora-stats/api/graph/model"
	"aurora-stats/api/internal/people"
	"aurora-stats/api/internal/wheel"
	"context"
	"errors"
	"strconv"
)

// CreatePerson is the resolver for the createPerson field.
func (r *mutationResolver) CreatePerson(ctx context.Context, firstName string, lastName string) (*model.InsertResponse, error) {
	personID := people.CreatePerson(ctx, firstName, lastName)

	// returns the new person with their DB id
	return &model.InsertResponse{ID: strconv.FormatInt(personID, 10)}, nil
}

// DeletePerson is the resolver for the deletePerson field.
func (r *mutationResolver) DeletePerson(ctx context.Context, id string) (*model.DeleteResponse, error) {
	people.DeletePerson(ctx, id)

	return &model.DeleteResponse{ID: id, Success: true}, nil
}

// AddWheelOption is the resolver for the addWheelOption field.
func (r *mutationResolver) AddWheelOption(ctx context.Context, name string) (*model.InsertResponse, error) {
	wheelOptionID, err := wheel.SaveWheelOption(name)

	if err != nil {
		return nil, errors.New("there was an error saving the data")
	}

	return &model.InsertResponse{ID: strconv.FormatInt(wheelOptionID, 10)}, nil
}

// AddWheelRun is the resolver for the addWheelRun field.
func (r *mutationResolver) AddWheelRun(ctx context.Context, date string, winnerID int, resultID int) (*model.InsertResponse, error) {
	wheelRunID := wheel.SaveWheelRun(date, winnerID, resultID)

	return &model.InsertResponse{ID: strconv.FormatInt(wheelRunID, 10)}, nil
}

// People is the resolver for the people field.
func (r *queryResolver) People(ctx context.Context) ([]*model.Person, error) {
	var resultsPeople []*model.Person

	for _, person := range people.GetAll(ctx) {
		resultsPeople = append(resultsPeople, &model.Person{ID: strconv.FormatInt(person.ID, 10), FirstName: person.FirstName, LastName: person.LastName})
	}

	return resultsPeople, nil
}

// WheelOptions is the resolver for the wheelOptions field.
func (r *queryResolver) WheelOptions(ctx context.Context) ([]*model.WheelOption, error) {
	var resultsWheelOptions []*model.WheelOption

	for _, wheelOption := range wheel.GetAllWheelOptions() {
		resultsWheelOptions = append(resultsWheelOptions, &model.WheelOption{ID: strconv.FormatInt(wheelOption.ID, 10), Name: wheelOption.Name})
	}

	return resultsWheelOptions, nil
}

// WheelResults is the resolver for the wheelResults field.
func (r *queryResolver) WheelResults(ctx context.Context, from string, to *string) ([]*model.WheelResult, error) {
	var wheelWinResults []*model.WheelResult

	for _, wheelWin := range wheel.GetWheelRuns(from, to) {
		wheelWinResults = append(wheelWinResults, &model.WheelResult{
			ID:   wheelWin.ID,
			Date: wheelWin.Date,
			Winner: &model.Person{
				ID:        strconv.FormatInt(wheelWin.Winner.ID, 10),
				FirstName: wheelWin.Winner.FirstName,
				LastName:  wheelWin.Winner.LastName,
			},
			Prize: &model.WheelOption{
				ID:   strconv.FormatInt(wheelWin.Prize.ID, 10),
				Name: wheelWin.Prize.Name,
			},
		})
	}

	return wheelWinResults, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
