apiVersion: v2
name: aurora-stats-website
description: A Helm chart for Kubernetes
version: '15'
appVersion: '15'

type: application
version: 0.1.0

dependencies:
  - name: application
    version: 1.x.x
    repository: "@sbg-local"