echo "** Creating default Users **"

mysql -u root -p$MYSQL_ROOT_PASSWORD --execute \
"CREATE USER '$FLYWAY_USER'@'%' IDENTIFIED WITH mysql_native_password BY '$FLYWAY_PASSWORD';
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$FLYWAY_USER'@'%';
CREATE USER '$READ_USER'@'%' IDENTIFIED BY '$READ_PASSWORD';
GRANT SELECT ON $MYSQL_DATABASE.* TO '$READ_USER'@'%';
CREATE USER '$WRITE_USER'@'%' IDENTIFIED BY '$WRITE_PASSWORD';
GRANT DELETE, INSERT, UPDATE, LOCK TABLES, CREATE TEMPORARY TABLES, EXECUTE ON $MYSQL_DATABASE.* TO '$WRITE_USER'@'%';"

echo "** Default users created **"