echo "** Creating default Users **"

mysql -u root -p$MYSQL_ROOT_PASSWORD --execute \
"CREATE USER '$FLYWAY_USER'@'%' IDENTIFIED WITH mysql_native_password BY '$FLYWAY_PASSWORD';
GRANT ALL PRIVILEGES ON $MYSQL_DATABASE.* TO '$FLYWAY_USER'@'%';
CREATE USER '$API_USER'@'%' IDENTIFIED BY '$API_PASSWORD';
GRANT DELETE, INSERT, UPDATE, SELECT, LOCK TABLES, CREATE TEMPORARY TABLES, EXECUTE ON $MYSQL_DATABASE.* TO '$API_USER'@'%';"

echo "** Default users created **"